"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var prototype_1 = require("./prototype");
var builder_1 = require("./builder");
var factory_1 = require("./factory");
var spinner = new prototype_1.GameObject('Spinner !', [0, 0]);
spinner.describe();
var anotherSpinner = spinner.clone();
anotherSpinner.describe();
var classFactory = new factory_1.ClassFactory();
var warrior = classFactory.createCharacter('Warrior');
var gameCharBuilder = new builder_1.GameCharacterBuilder('Cornel', warrior);
var gameChar = gameCharBuilder.build();
gameChar.describe();
gameCharBuilder.setWeapon('Atiesh, Greatstaff of the Guardian');
gameChar.describe();
gameCharBuilder.setArmor('the Frostfire Regalia');
gameChar.describe();
gameChar.attack();
var wizard = classFactory.createCharacter('Wizard');
gameCharBuilder.setClass(wizard);
gameChar.describe();
gameChar.attack();
